### PR TITLE
Implemented Line Height

### PR DESCRIPTION
**Pull request by Shubhamverma2796**
### Summary of changes
Users can increase/decrease line height by clicking on the Increase/decrease line height.

### Testing instructions
Just check you are able to increase/decrease lineheight. Do not forget to check for persistent session and reset button.

### CODE REVIEW

**Comment by apapageorgiou** [comment]
Icons are missing

**Comment by apapageorgiou** [comment]
Please, also, capitalize the first letter of each word, similarly to the already typography rules of the toolbar. 

e.g. increase line height -> Increase Line Height

**Comment by Shubhamverma2796** [comment]
> Please, also, capitalize the first letter of each word, similarly to the already typography rules of the toolbar.
> 
> e.g. increase line height -> Increase Line Height

please see https://github.com/joomla-projects/gsoc22_accessibility-plugin/pull/6

**Comment by apapageorgiou** [comment]
Tested successfully

**Pull request merged**
